export const otherUniversityOption = 'Other';

export const australianUniversityOptions = [
  'Adelaide University',
  'Australian Catholic University',
  'Australian National University',
  'Australian University of Theology',
  'Avondale University',
  'Bond University',
  'Carnegie Mellon University Australia',
  'Central Queensland University',
  'Charles Darwin University',
  'Charles Sturt University',
  'Curtin University',
  'Deakin University',
  'Edith Cowan University',
  'Federation University Australia',
  'Flinders University',
  'Griffith University',
  'James Cook University',
  'La Trobe University',
  'Macquarie University',
  'Monash University',
  'Murdoch University',
  'Queensland University of Technology',
  'RMIT University',
  'Southern Cross University',
  'Swinburne University of Technology',
  'Torrens University Australia',
  'University of Canberra',
  'University of Divinity',
  'University of Melbourne',
  'University of New England',
  'University of New South Wales',
  'University of Newcastle',
  'University of Notre Dame Australia',
  'University of Queensland',
  'University of Southern Queensland',
  'University of Sydney',
  'University of Tasmania',
  'University of Technology Sydney',
  'University of the Sunshine Coast',
  'University of Western Australia',
  'University of Wollongong',
  'Victoria University',
  'Western Sydney University',
  otherUniversityOption,
];
