import {
  ArrowRight,
  BookOpen,
  Calendar,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  Clock,
  DollarSign,
  Download,
  FileDown,
  Globe,
  GraduationCap,
  LayoutDashboard,
  LogOut,
  Mail,
  MapPin,
  Pencil,
  Phone,
  Plus,
  Search,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

const icons = {
  graduation: GraduationCap,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  user: User,
  mail: Mail,
  users: Users,
  dollar: DollarSign,
  mapPin: MapPin,
  globe: Globe,
  search: Search,
  dashboard: LayoutDashboard,
  calendar: Calendar,
  logout: LogOut,
  plus: Plus,
  edit: Pencil,
  trash: Trash2,
  x: X,
  check: Check,
  alert: TriangleAlert,
  upload: Upload,
  download: Download,
  csvDownload: FileDown,
  phone: Phone,
  clock: Clock,
  book: BookOpen,
  historicalStats: ChartNoAxesCombined,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, className = 'h-5 w-5', ...props }: LucideProps & { name: IconName }) {
  const LucideIcon = icons[name];
  return <LucideIcon className={className} aria-hidden="true" {...props} />;
}
